In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Upload Data

In [12]:
df = pd.read_csv("../Data/Tadawul_stcks_23_4.xls")

## EDA

In [13]:
df.head()

,symbol,name,trading_name,sectoer,date,open,high,low,close,change,perc_Change,volume_traded,value_traded,no_trades
0,2030,Saudi Arabia Refineries Co.,SARCO,Energy,2020-04-23,31.8,31.8,31.45,31.60,0.25,0.80,230790.0,7295880.55,507.0
1,2030,Saudi Arabia Refineries Co.,SARCO,Energy,2020-04-22,30.5,31.4,30.30,31.35,-0.35,-1.10,422695.0,13113020.10,1015.0
2,2030,Saudi Arabia Refineries Co.,SARCO,Energy,2020-04-21,31.7,32.3,31.30,31.70,-0.75,-2.31,266845.0,8497563.05,668.0
3,2030,Saudi Arabia Refineries Co.,SARCO,Energy,2020-04-20,32.7,32.9,32.10,32.45,-0.25,-0.76,254463.0,8271461.45,557.0
4,2030,Saudi Arabia Refineries Co.,SARCO,Energy,2020-04-19,32.5,32.8,32.45,32.70,0.50,1.55,199425.0,6500652.35,498.0

In [14]:
df.shape

(6992, 14)

<span style="color:red">PROBLEM IN DATA TYPES</span>

In [15]:
df.dtypes

symbol              int64
name               object
trading_name       object
sectoer            object
date               object
open              float64
high              float64
low               float64
close             float64
change            float64
perc_Change       float64
volume_traded     float64
value_traded      float64
no_trades         float64
dtype: object

<span style="color:red">NULL VALUES</span>

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6992 entries, 0 to 6991
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   symbol          6992 non-null   int64
 1   name            6992 non-null   object
 2   trading_name    6992 non-null   object
 3   sectoer         6992 non-null   object
 4   date            6992 non-null   object
 5   open            6830 non-null   float64
 6   high            6830 non-null   float64
 7   low             6830 non-null   float64
 8   close           6992 non-null   float64
 9   change          6992 non-null   float64
 10  perc_Change     6992 non-null   float64
 11  volume_traded   6992 non-null   float64
 12  value_traded    6992 non-null   float64
 13  no_trades       6992 non-null   float64
dtypes: float64(9), int64(1), object(4)
memory usage: 764.9+ KB

<span style="color:red">COLUMN NAMES</span>

In [22]:
df.columns

Index(['symbol', 'name', 'trading_name ', 'sectoer', 'date', 'open', 'high',
       'low', 'close', 'change', 'perc_Change', 'volume_traded ',
       'value_traded', 'no_trades '],
      dtype='object')

In [21]:
df.describe()

,symbol,open,high,low,close,change,perc_Change,volume_traded,value_traded,no_trades
count,6992.000000,6830.000000,6830.000000,6830.000000,6992.000000,6992.000000,6992.000000,6.992000e+03,6.992000e+03,6992.000000
mean,4113.914903,24.659725,25.182366,24.196105,24.328474,-0.089798,-0.336230,1.136108e+06,2.358603e+07,1076.635584
std,2257.109245,22.733866,23.249451,22.309276,22.576215,1.266593,3.683778,3.011323e+06,6.681986e+07,1648.871027
min,1010.000000,5.740000,5.950000,5.740000,5.390000,-14.000000,-12.880000,0.000000e+00,0.000000e+00,0.000000
25%,2200.000000,10.360000,10.580000,10.140000,10.220000,-0.340000,-1.850000,1.980355e+05,3.322344e+06,336.000000
50%,4040.000000,15.810000,16.120000,15.440000,15.500000,0.000000,0.000000,4.225855e+05,8.190636e+06,639.500000
75%,5110.000000,29.700000,30.300000,29.050000,29.060000,0.250000,1.480000,9.724018e+05,1.999385e+07,1193.000000
max,8312.000000,157.000000,163.000000,155.400000,158.800000,12.400000,19.930000,6.831751e+07,1.064690e+09,26201.000000

In [23]:
df.describe(include='object')

                               name trading_name      sectoer        date
count                          6992          6992        6992        6992
unique                          200           200          11          35
top     Saudi Arabia Refineries Co.         SARCO  Financials  2020-04-23
freq                             35            35        1645         200

In [25]:
df['sectoer'].unique()

array(['Energy', 'Materials', 'Industrials', 'Consumer Discretionary',
       'Communication Services', 'Consumer Staples', 'Health Care',
       'Financials', 'Information Technology', 'Utilities', 'Real Estate'],
      dtype=object)

In [26]:
df['trading_name '].unique()

array(['SARCO', 'SAUDI ARAMCO', 'PETRO RABIGH', 'BAHRI', 'ALDREES',
       'TAKWEEN', 'MEPCO', 'BCI', 'MAADEN', 'ASLAK', 'ALYAMAMAH STEEL',
       'SSP', 'CHEMANOL', 'PETROCHEM', 'SABIC', 'SAFCO', 'TASNEE', 'NGC',
       'ZOUJAJ', 'ALUJAIN', 'FIPCO', 'APC', 'NAMA CHEMICALS',
       'MAADANIYAH', 'ZAMIL INDUST', 'SIIG', 'YANSAB', 'SPM', 'SIPCHEM',
       'ADVANCED', 'SAUDI KAYAN', 'HCC', 'NAJRAN CEMENT', 'CITY CEMENT',
       'NORTHERN CEMENT', 'UACC', 'OASIS', 'ALKATHIRI', 'ACC', 'YSCC',
       'SAUDI CEMENT', 'QACCO', 'SPCC', 'YCC', 'EPCCO', 'TCC',
       'JOUF CEMENT', 'ASTRA INDUSTRIAL', 'BAWAN', 'EIC', 'ALKHODARI',
       'SAUDI CERAMICS', 'SAUDI CABLE', 'ADC', 'AMIANTIT', 'ALBABTAIN',
       'SVCP', 'MESC', 'SIECO', 'MAHARAH', 'SPPC', 'CATERING', 'SISCO',
       'SGS', 'SAPTCO', 'BATIC', 'BUDGET SAUDI', 'ALSORAYAI GROUP',
       'SIDC', 'ALABDULLATIF', 'LAZURDE', 'ALASEEL', 'FITAIHI GROUP',
       'SEERA', 'ALHOKAIR GROUP', 'FITNESS TIME', 'DUR', 'TECO',
       'ALKHALEEJ TRNG', 'NCLE', 'ATAA', 'HERFY FOODS', 'RAYDAN',
       'TAPRCO', 'SRMG', 'SHAKER', 'EXTRA', 'SACO', 'SASCO', 'BAAZEEM',
       'JARIR', 'ABO MOATI', 'ALHOKAIR', 'A.OTHAIM MARKET',
       'FARM SUPERSTORES', 'ANAAM HOLDING', 'THIMAR', 'SAVOLA GROUP',
       'WAFRAH', 'SADAFCO', 'ALMARAI', 'HB', 'NADEC', 'GACO', 'TADCO',
       'SFICO', 'SHARQIYAH DEV', 'ALJOUF', 'JAZADCO', 'CHEMICAL',
       'MOUWASAT', 'DALLAH HEALTH', 'CARE', 'ALHAMMADI',
       'SAUDI GERMAN HOSPTL', 'SULAIMAN ALHABIB', 'SPIMACO', 'RIBL',
       'BJAZ', 'SAIB', 'BSFR', 'SABB', 'ANB', 'SAMBA', 'ALRAJHI',
       'ALBILAD', 'ALINMA', 'NCB', 'SAIC', 'ASEER', 'ALBAHA', 'KINGDOM',
       'TAWUNIYA', 'JAZIRA TAKAFUL', 'MALATH INSURANCE', 'MEDGULF',
       'ALLIANZ SF', 'SALAMA', 'WALAA', 'ARABIAN SHIELD', 'SABB TAKAFUL',
       'SAICO', 'WAFA INSURANCE', 'GULF UNION', 'ATC', 'ALAHLIA', 'ACIG',
       'AICC', 'ALETIHAD', 'ALSAGR INSURANCE', 'UCA', 'SAUDI RE',
       'BUPA ARABIA', 'ALRAJHI TAKAFUL', 'CHUBB', 'AXA COOPERATIVE',
       'GULF GENERAL', 'BURUJ', 'ALALAMIYA', 'SOLIDARITY', 'WATANIYA',
       'AMANA INSURANCE', 'ENAYA', 'ALINMA TOKIO M', 'MIS', 'ARAB SEA',
       'STC', 'ETIHAD ETISALAT', 'ZAIN KSA', 'ATHEEB TELECOM', 'GASCO',
       'SAUDI ELECTRICITY', 'RIYAD REIT', 'ALJAZIRA REIT',
       'JADWA REIT ALHARAMAIN', 'TALEEM REIT', 'AL MAATHER REIT',
       'MUSHARAKA REIT', 'MULKIA REIT', 'MASHAAR REIT', 'ALAHLI REIT 1',
       'DERAYAH REIT', 'Al RAJHI REIT', 'JADWA REIT SAUDI',
       'SEDCO CAPITAL REIT', 'SWICORP WABEL REIT', 'MEFIC REIT',
       'BONYAN REIT', 'ALKHABEER REIT', 'SRECO', 'TAIBA', 'MCDC', 'ARDCO',
       'EMAAR EC', 'RED SEA', 'JABAL OMAR', 'DAR ALARKAN', 'KEC',
       'ALANDALUS', 'ALMRAKEZ'], dtype=object)

In [27]:
df['sectoer'].value_counts()

sectoer
Financials                1645
Materials                 1470
Real Estate                980
Consumer Discretionary     840
Industrials                700
Consumer Staples           560
Health Care                273
Communication Services     210
Energy                     175
Utilities                   70
Information Technology      69
Name: count, dtype: int64

In [28]:
df['trading_name '].value_counts()

trading_name
SARCO               35
ALBILAD             35
NCB                 35
SAIC                35
ASEER               35
                    ..
LAZURDE             35
ALASEEL             35
ALMRAKEZ            35
ARAB SEA            34
SULAIMAN ALHABIB    28
Name: count, Length: 200, dtype: int64